/* WELL */
export const RECIEVE_WELL_TYPES = 'RECIEVE_WELL_TYPES'
export const RECIEVE_WELLS = 'RECIEVE_WELLS'
export const DELETE_WELL = 'DELETE_WELL'

/* FIELD */
export const RECIEVE_FIELDS = 'RECIEVE_FIELDS'
export const DELETE_FIELD = 'DELETE_FIELD'

/* SHOP */
export const RECIEVE_SHOPS = 'RECIEVE_SHOPS'
export const DELETE_SHOP = 'DELETE_SHOP'

/* COMPANY */
export const RECIEVE_COMPANIES = 'RECIEVE_COMPANIES'
export const DELETE_COMPANY = 'DELETE_COMPANY'

/* Dialog element */
export const SET_RESULT_CONFIRM_DIALOG = 'SET_RESULT_CONFIRM_DIALOG'
export const SHOW_CONGRATULATION_DIALOG = 'SHOW_CONGRATULATION_DIALOG'
export const CLEAR_MESSAGE_DIALOG = 'CLEAR_MESSAGE_DIALOG'
export const SET_MESSAGE_DIALOG = 'SET_MESSAGE_DIALOG'

/* Busy element */
export const SET_LOADING = 'SET_LOADING'

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_MESSAGES = 'SET_MESSAGES'
export const SET_ERRORS = 'SET_ERRORS'
